name: CI

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
          
      # Install dependencies
      - run: npm install
      
      # Run tests
      - run: npx cypress run
      
      - name: Upload videos
        uses: actions/upload-artifact@v.2.2.3
        if: always()
        with:
          name: videos
          path: cypress/videos
